### ISSUE TITLE
Having nan value for all the losses

### ISSUE THREAD

**Issue by arnobanu** [SharifAmit/RVGAN#20] opened 2023-02-02 17:10 UTC
After running train.py i am having nan value for all the losses.
Code is running on:
tensorflow-gpu = 2.0.3
GPU - 3090 Ti

![Capture](https://user-images.githubusercontent.com/88239402/216393875-0ba14b64-fcab-41fe-ae2d-bc66d025411f.PNG)

**Comment by SharifAmit** [comment] 2023-02-02 20:18
This is duplicate of issue https://github.com/SharifAmit/RVGAN/issues/5 . And not related to our code but rather tensorflow library. I'm closing this issue.

**Closed as completed** 2023-02-02 23:50 UTC
